apiVersion: apm.k8s.elastic.co/v1
kind: ApmServer
metadata:
  name: apm-server
  namespace: eck-monitoring
spec:
  version: 7.10.1
  count: 1
  elasticsearchRef:
    name: elasticsearch-gamma
  kibanaRef:
    name: kibana
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  podTemplate:
    spec:
      containers:
      - name: apm-server
        resources:
          requests:
            memory: 500Mi
            cpu: 0.2
          limits:
            memory: 2Gi
            cpu: 1
