apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elasticsearch-gamma
  namespace: logging-apps
  labels:
    logging: es-apps
spec:
  version: 7.10.1
  nodeSets:
  - name: default
    count: 2
    config:
      node.store.allow_mmap: true
      node.master: true
      node.data: true
      node.ingest: true
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 80Gi
        storageClassName: karbon-dr
    podTemplate:
      spec:
        tolerations:
        - key: "type"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: "type"
                  operator: In
                  values:
                  - "monitoring"
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: logging
                    operator: In
                    values:
                    - es-apps
                topologyKey: topology.kubernetes.io/zone
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        containers:
        - name: elasticsearch
          env:
          - name: ES_JAVA_OPTS
            value: -Xms6g -Xmx6g
          resources:
            requests:
              cpu: 2000m
              memory: 7Gi
            limits:
              memory: 7Gi
              cpu: 2000m