apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mariadb-logs
  namespace: concentrateur-prod
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: share-concentrateur
