apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: kafka-topic-test
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: kafka-topic-test

