apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: fintfjchannelcalc-in
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: finTFJChannelCalc-in
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: fintfjchannelcalc-out
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: finTFJChannelCalc-out
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c11
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C11
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c3
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 1
  topicName: Q_C3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c38
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 1
  topicName: Q_C38
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 1
  topicName: Q_C381
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381gag
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381GAG
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381jug
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381JUG
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381juo
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381JUO
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381jup
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381JUP
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381pla
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381PLA
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381qap
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381QAP
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381qip
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381QIP
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381quu
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381QUU
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381r
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 1
  topicName: Q_C381R
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381res
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381RES
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381trc
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381TRC
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381tro
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381TRO
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c4
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 5
  replicas: 3
  topicName: Q_C4
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c41
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 5
  replicas: 3
  topicName: Q_C41
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c41r
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 5
  replicas: 3
  topicName: Q_C41R
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c8
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C8
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9arr
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9ARR
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9flx
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9FLX
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9gag
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9GAG
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9jug
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9JUG
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9juo
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9JUO
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9jup
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9JUP
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9off
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 1
  topicName: Q_C9OFF
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9par
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9PAR
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9pil
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9PIL
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9pla
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9PLA
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9qap
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9QAP
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9qip
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9QIP
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9quu
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9QUU
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9rec
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9REC
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9res
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9RES
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9tra
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9TRA
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9trc
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9TRC
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c9tro
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C9TRO
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-cfj
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_CFJ
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-finsession
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: Q_FinSession
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i0
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_I0
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i0r
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_I0R
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i10
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: Q_I10
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i11
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: Q_I11
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i3
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_I3
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i38
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_I38
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i4
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 4
  replicas: 3
  topicName: Q_I4
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i5
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 3
  topicName: Q_I5
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i6
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 3
  topicName: Q_I6
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i7
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 1
  replicas: 3
  topicName: Q_I7
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i71
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_I71
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-i72
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_I72
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-ifj
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_IFJ
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-rfj
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: Q_RFJ
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: rejeti0channel-in
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: rejetI0Channel-in
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: rejeti0channel-out
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: rejetI0Channel-out
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfj-topic
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfj-topic
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfj-topic-externe
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfj-topic-externe
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjchannel-in
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjChannel-in
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjchannel-out
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjChannel-out
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjchannelcalc-in
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjChannelCalc-in
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjchannelcalc-out
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjChannelCalc-out
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjchannelexterne-in
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjChannelExterne-in
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjchannelexterne-out
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjChannelExterne-out
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjcsvchannelcalc-in
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjCSVChannelCalc-in
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: tfjcsvchannelcalc-out
  namespace: {{ .Release.Namespace }}
spec:
  config: {}
  partitions: 1
  replicas: 1
  topicName: tfjCSVChannelCalc-out
---
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: {{ .Values.clusterName }}
  name: q-c381pi5
  namespace: {{ .Release.Namespace }}
spec:
  partitions: 3
  replicas: 3
  topicName: Q_C381PI5
---

