apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafkadrop-preprod
  namespace: argocd
spec:  
  project: default
  source:
    path: kafkadrop/
    repoURL: https://github.com/OmarAMAOUN/gamma-infrastructure.git
    targetRevision: HEAD
    helm:
      values: |-
        replicaCount: 1
        image:
          repository: obsidiandynamics/kafdrop
          tag: 3.29.0
        kafka:
          brokerConnect: gamma-cluster-kafka-bootstrap.preprod-kafka.svc.cluster.local:9092
          properties: ""
          truststore: ""
          keystore: ""
          propertiesFile: "kafka.properties"
          truststoreFile: "kafka.truststore.jks"
          keystoreFile: "kafka.keystore.jks"      
        host:
        server:
          port: 9000
          servlet:
            contextPath: /
        service:
          annotations: {}
          type: ClusterIP
          port: 9000
          nodePort: 30900
        ingress:
          enabled: true
          annotations:
            # # type of authentication
            # nginx.ingress.kubernetes.io/auth-type: basic
            # # name of the secret that contains the user/password definitions
            # nginx.ingress.kubernetes.io/auth-secret: basic-auth
            # # message to display with an appropriate context why the authentication is required
            # nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'
          path: /
          hosts: 
          - kafkadrop-preprod.sorec.ma
          tls: []
        jvm:
          opts: "-Xms256M -Xmx256M"
        resources:
          limits:
            cpu: 200m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 512Mi
        tolerations:
        - effect: NoSchedule
          key: type
          operator: Equal
          value: monitoring
        affinity: 
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: type
                  operator: In
                  values:
                  - monitoring

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: monitoring-apps
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
