apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
spec:
  destination:
    namespace: keycloak-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      values: |-
        #
    path: keycloak/
    repoURL: https://github.com/OmarAMAOUN/gamma-infractructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
