apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gamma-logging
  namespace: argocd
spec:
  destination:
    namespace: logging-apps
    server: https://kubernetes.default.svc
  project: default
  source:
    path: eck/
    repoURL: https://github.com/OmarAMAOUN/gamma-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true