apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mariadb-prod
  namespace: argocd
spec:
  destination:
    namespace: concentrateur-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      #values: |-
      valueFiles:
        - values-prod.yaml

    path: mariadb/
    repoURL: https://github.com/itmwiw/gamma-infrastructure.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true