apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/itmwiw/gamma-infrastructure.git'
    path: storage/
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: storage
  syncPolicy:
    syncOptions:
      - CreateNamespace=true