apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-concentrateur-role-binding
  namespace: concentrateur-prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sa-podsaccess
subjects:
- kind: ServiceAccount
  name: concentrateurpodsaccess
  namespace: concentrateur-prod
