# Must change keycloak version from latest to 16.1.1
keycloak:
  enabled: true
  
  global:
    storageClass: "default-storageclass"
  
  image:
    registry: docker.io
    repository: bitnami/keycloak
    tag: 15.0.2-debian-10-r45
  
  serviceDiscovery:
    enabled: true
    ## @param serviceDiscovery.protocol Sets the protocol that Keycloak nodes would use to discover new peers
    ## Available protocols can be found at http://www.jgroups.org/javadoc3/org/jgroups/protocols/
    ##
    protocol: kubernetes.KUBE_PING
    ## @param serviceDiscovery.properties Properties for the discovery protocol set in `serviceDiscovery.protocol` parameter
    ## List of key=>value pairs
    ## Example:
    ## properties:
    ##   - datasource_jndi_name=>"java:jboss/datasources/KeycloakDS"
    ##   - initialize_sql=>"CREATE TABLE IF NOT EXISTS JGROUPSPING ( own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, created timestamp default current_timestamp, ping_data BYTEA, constraint PK_JGROUPSPING PRIMARY KEY (own_addr, cluster_name))"
    ##
    properties: []
    ## @param serviceDiscovery.transportStack Transport stack for the discovery protocol set in `serviceDiscovery.protocol` parameter
    ##
    transportStack: tcp
  ## Keycloak cache settings

postgresql-ha:
  enabled: false

  global:
    storageClass: "default-storageclass"
  
  postgresqlImage:
    registry: docker.io
    repository: bitnami/postgresql-repmgr
    tag: 11.13.0-debian-10-r40
  
  postgresql:
    replicaCount: 2
    resources:
      limits:
         cpu: 500m
         memory: 512Mi
      requests:
         cpu: 200m
         memory: 512Mi
      
  pgpoolImage:
    registry: docker.io
    repository: bitnami/pgpool
    tag: 4.2.5-debian-10-r8
  
  pgpool:
    replicaCount: 2
    resources:
      limits:
         cpu: 250m
         memory: 256Mi
      requests:
         cpu: 250m
         memory: 256Mi
      
  metricsImage:
    registry: docker.io
    repository: bitnami/postgres-exporter
    tag: 0.10.0-debian-10-r68
  
  metrics:
    enabled: false
    resources:
      ## Example:
      ## limits:
      ##    cpu: 250m
      ##    memory: 256Mi
      ##
      limits: {}
      ## Examples:
      ## requests:
      ##    cpu: 250m
      ##    memory: 256Mi
      ##
      requests: {}
  
  persistence:
    enabled: true
    storageClass: "default-storageclass"
    size: 50Gi

