apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mariadb-{{ .Values.env }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: transaction
    argocd.argoproj.io/instance: mariadb-{{ .Values.env }}
    helm.sh/chart: transaction-6.0.5
  name: mariadb-{{ .Values.env }}-transaction-instance
  namespace: concentrateur-{{ .Values.env }}
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: mysql
    nodePort: 32498
    port: 3306
    protocol: TCP
    targetPort: mysql
  selector:
    app.kubernetes.io/instance: mariadb-{{ .Values.env }}
    app.kubernetes.io/name: transaction
    statefulset.kubernetes.io/pod-name: mariadb-{{ .Values.env }}-transaction-0
  sessionAffinity: None
  type: NodePort