apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-operator
  namespace: argocd
spec:
  destination:
    namespace: keycloak-prod
    server: https://kubernetes.default.svc
  project: default
  source:
    path: keycloak-operator/
    repoURL: https://github.com/OmarAMAOUN/gamma-infrastructure.git
    targetRevision: HEAD
    directory:
      recurse: true
  syncPolicy:
    syncOptions:
    - CreateNamespace=true