env: preprod
clusterName: gamma-cluster
kafka:
  replicas: 3
  config:
    auto.create.topics.enable: false
    default.replication.factor: 3
    group.initial.rebalance.delay.ms: 5000
    inter.broker.protocol.version: "2.7"
    log.message.format.version: "2.7"
    log.retention.hours: 24
    num.io.threads: 16
    num.network.threads: 64
    offsets.topic.replication.factor: 3
    queued.max.requests: 1000
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
    message.max.bytes: 20000000
    replica.fetch.max.bytes: 20000000
    replica.fetch.response.max.bytes: 20000000
    min.insync.replicas: 2
    offsets.commit.required.acks: -1
  storage:
    storageClass: default-storageclass
    size: 100Gi
  jvmOptions:
    -Xms: 2048m
    -Xmx: 2048m
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 2Gi

zookeeper:
  replicas: 3
  storage:
    storageClass: default-storageclass
    size: 10Gi
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  jvmOptions:
    -Xms: 1024m
    -Xmx: 1024m