env: prod
clusterName: gamma-cluster-prod
kafka:
  replicas: 3
  config:
    auto.create.topics.enable: false
    default.replication.factor: 3
    group.initial.rebalance.delay.ms: 5000
    inter.broker.protocol.version: '2.7'
    log.cleanup.policy: delete
    log.message.format.version: '2.7'
    log.roll.ms: 86400000
    log.retention.ms: 86400000
    message.max.bytes: 20000000
    num.io.threads: 16
    num.network.threads: 64
    offsets.topic.replication.factor: 3
    queued.max.requests: 1000
    replica.fetch.max.bytes: 20000000
    replica.fetch.response.max.bytes: 20000000
    transaction.state.log.min.isr: 2
    transaction.state.log.replication.factor: 3
    min.insync.replicas: 2
    offsets.commit.required.acks: -1
  storage:
    storageClass: karbon-dr
    size: 100Gi
  jvmOptions:
    -Xms: 4096m
    -Xmx: 4096m
  resources:
    limits:
      cpu: 2
      memory: 6Gi
    requests:
      cpu: 2
      memory: 6Gi
  additionalListners:
  - name: external
    authentication:
      type: tls
    authorization:
      type: simple
    configuration:
      preferredNodePortAddressType: InternalDNS
    port: 9094
    tls: true
    type: ingress
    configuration:
        bootstrap:
          host: bootstrap.kafka.sorec.ma
        brokers:
        - broker: 0
          host: broker-0.kafka.sorec.ma
        - broker: 1
          host: broker-1.kafka.sorec.ma
        - broker: 2
          host: broker-2.kafka.sorec.ma


zookeeper:
  replicas: 3
  storage:
    storageClass: default-storageclass
    size: 10Gi
  resources:
    limits:
      cpu: 2
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi
  jvmOptions:
    -Xms: 1024m
    -Xmx: 1024m
