apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgresql
spec:
  ports:
  - name: postgresql
    port: 5432
    protocol: TCP
    targetPort: postgresql
  selector:
    app.kubernetes.io/component: pgpool
    app.kubernetes.io/instance: keycloak
    app.kubernetes.io/name: postgresql-ha
  sessionAffinity: None
  type: ClusterIP